"""
Django settings for dns_resolver project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import secrets
import sys
import time
from pathlib import Path

from dotenv import load_dotenv

# Statik dosya sürüm damgası (önbellek kırma). Her process başlangıcında/deploy'da
# değişir → base.html'de "?v={{ static_v }}" ile tarayıcı yeni JS/CSS'i çeker,
# whitenoise'ın 60 sn cache'ine ya da bellekteki eski script'e takılmaz.
STATIC_VERSION = str(int(time.time()))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Resolver ile aynı .env dosyasını yükle (proje kökünde, dns_resolver'ın bir üstü).
# db_ops/db_core.py ile birebir aynı DB_* değişkenlerini paylaşmak için.
load_dotenv(BASE_DIR.parent / ".env")

# Proje kökünü (resolver ile paylaşılan leaf modüller: logcrypto) import yoluna
# ekle — panel process'inin cwd'si dns_resolver/ olduğundan kök otomatik yolda değil.
sys.path.insert(0, str(BASE_DIR.parent))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
def _get_or_create_secret_key():
    """
    DJANGO_SECRET_KEY verilmemişse (ya da BOŞSA), kuruluma özel kalıcı bir
    anahtar üretip saklar. Anahtar SQLite ile aynı (kalıcı) dizinde tutulur,
    böylece konteyner yeniden oluşturulsa da oturumlar/çerezler bozulmaz.
    """
    db_path = os.getenv('DJANGO_DB_PATH')
    key_dir = Path(db_path).parent if db_path else BASE_DIR
    key_file = key_dir / 'secret_key.txt'
    if key_file.exists():
        return key_file.read_text().strip()
    key = ''.join(secrets.choice('abcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*(-_=+)') for _ in range(50))
    try:
        key_dir.mkdir(parents=True, exist_ok=True)
        key_file.write_text(key)
        os.chmod(key_file, 0o600)
    except OSError:
        pass  # yazamadıysak (salt-okunur fs) süreç-ömrü boyunca geçerli anahtarla devam
    return key


# Öncelik: ortam değişkeni (boş değilse) -> kalıcı üretilen anahtar.
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY') or _get_or_create_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
# Varsayılan KAPALI (güvenli); yerel geliştirmede DJANGO_DEBUG=True ile açılır.
DEBUG = os.getenv('DJANGO_DEBUG', 'False').lower() == 'true'

# Virgülle ayrılmış host listesi (ör. "dns.example.com,127.0.0.1").
ALLOWED_HOSTS = [h.strip() for h in os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]

# CSRF: form gönderimi bir domain/ters proxy (Cloudflare) arkasından geldiğinde
# origin doğrulaması için güvenilir origin listesi (ör. "https://dns.example.com").
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.getenv('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]

# Güvenli çerezler + tarayıcı sertleştirme başlıkları. Panel normalde HTTPS
# (TLS / Cloudflare) arkasında çalışır → varsayılan güvenli. Düz-HTTP yerel
# geliştirmede DJANGO_SECURE_COOKIES=False ile kapatılır (aksi halde tarayıcı
# çerezi HTTPS olmayan bağlantıda göndermez ve giriş yapılamaz).
_SECURE_COOKIES = os.getenv('DJANGO_SECURE_COOKIES', 'True').lower() == 'true'
SESSION_COOKIE_SECURE = _SECURE_COOKIES
CSRF_COOKIE_SECURE = _SECURE_COOKIES
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
# Ters proxy / Cloudflare Tunnel TLS'i sonlandırıp container'a düz HTTP iletir; bu
# başlıkla Django isteği HTTPS sayar (request.is_secure() doğru + güvenli çerez/HSTS
# çalışır). Panel yalnız 127.0.0.1'e + tünele bağlı olduğundan başlık sahtelenemez.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Oturum imzalı çerezde tutulur (DB'siz) → async view'lardan request.session
# erişimi SynchronousOnlyOperation üretmez. Kimlik doğrulamasız erişilemesin.
SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'
LOGIN_URL = '/giris/'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # DEBUG=False iken statik dosyaları (admin CSS vb.) uvicorn üstünden servis eder.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Dil secimi: oturum/cerez/Accept-Language -> request dili (set_language ile degisir)
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dns_resolver.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'dashboard.context_processors.static_version',
            ],
        },
    },
]

WSGI_APPLICATION = 'dns_resolver.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Django'nun KENDİ tabloları (auth/session/admin) SQLite'ta tutulur; küçük ve
# mysqlclient bağımlılığı gerektirmez. DNS sorgu verisi (dns_cache/users) buradan
# OKUNMAZ — o veri MariaDB'de yaşar ve dashboard/db.py içinde aiomysql ile
# asenkron okunur (resolver kod tabanıyla tutarlı). Django ORM'i MySQL'e hiç
# dokunmaz, dolayısıyla resolver'ın şemasını da migration'la bozamaz.

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # Container'da yazılabilir bir hacme (ör. /app/data) alınır ki
        # yeniden oluşturmalarda auth/session kaybolmasın.
        'NAME': os.getenv('DJANGO_DB_PATH') or (BASE_DIR / 'db.sqlite3'),
    }
}

# DNS sorgu veritabanı (MariaDB) — aiomysql bağlantı ayarları.
# db_ops/db_core.py ile AYNI DB_* ortam değişkenleri ve varsayılanları.
# Yerel geliştirmede DB_UNIX_SOCKET verilirse TCP yerine unix socket kullanılır.
DNS_DB = {
    'host': os.getenv('DB_HOST', 'localhost'),
    'port': int(os.getenv('DB_PORT', 3306)),
    'user': os.getenv('DB_USER', 'root'),
    'password': os.getenv('DB_PASSWORD', 'password'),
    'db': os.getenv('DB_NAME', 'dns_db'),
    'unix_socket': os.getenv('DB_UNIX_SOCKET') or None,
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'tr'          # varsayilan dil (msgid'ler Turkce); en -> locale/en

# Panel dilleri — topbar'daki dil degistirici (set_language) bunlari kullanir.
LANGUAGES = [
    ('tr', 'Turkce'),
    ('en', 'English'),
]

# Ceviri dosyalari (.po/.mo) burada; .mo yerelde derlenip commit'lenir
# (Docker imajina gettext gerekmesin).
LOCALE_PATHS = [BASE_DIR / 'locale']

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Sunucu hataları (500) DEBUG=False iken bile stdout'a düşsün ki `docker logs`
# ile teşhis edilebilsin (Django varsayılanı 500'leri konsola yazmaz).
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'root': {'handlers': ['console'], 'level': 'INFO'},
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}


STATIC_URL = 'static/'

# collectstatic çıktısı (imaj build'inde toplanır, whitenoise servis eder).
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        # Sıkıştırır ama manifest/hash kullanmaz (eksik-dosya katılığından kaçınır).
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}
