# Generated by Django 6.0.7 on 2026-08-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fp_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('ip', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.TextField(blank=True)),
                ('browser', models.CharField(blank=True, max_length=40)),
                ('os', models.CharField(blank=True, max_length=40)),
                ('device', models.CharField(blank=True, max_length=20)),
                ('screen', models.CharField(blank=True, max_length=40)),
                ('viewport', models.CharField(blank=True, max_length=40)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('platform', models.CharField(blank=True, max_length=64)),
                ('languages', models.CharField(blank=True, max_length=128)),
                ('color_depth', models.CharField(blank=True, max_length=8)),
                ('cpu', models.CharField(blank=True, max_length=8)),
                ('memory', models.CharField(blank=True, max_length=8)),
                ('gpu', models.CharField(blank=True, max_length=200)),
                ('touch', models.BooleanField(default=False)),
                ('canvas_hash', models.CharField(blank=True, max_length=64)),
                ('extra', models.TextField(blank=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(db_index=True)),
                ('hits', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
    ]
