# Generated by Django 6.0.7 on 2026-08-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_deviceprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceprofile',
            name='brave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deviceprofile',
            name='fp_protected',
            field=models.BooleanField(default=False),
        ),
    ]
