# Generated by Django 6.0.7 on 2026-08-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_deviceprofile_brave_deviceprofile_fp_protected'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceprofile',
            name='ips',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deviceprofile',
            name='volatile',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
