# Generated by Django 6.0.7 on 2026-08-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_deviceprofile_ips_deviceprofile_volatile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceprofile',
            name='canvas_hash',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='deviceprofile',
            name='gpu',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='deviceprofile',
            name='ip',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='deviceprofile',
            name='languages',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='deviceprofile',
            name='platform',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='deviceprofile',
            name='screen',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='deviceprofile',
            name='timezone',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='deviceprofile',
            name='viewport',
            field=models.TextField(blank=True),
        ),
    ]
